language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t amorrissett/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true amorrissett/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-sample"
    env: "Dockersample-env"
    bucket_name: "elasticbeanstalk-us-east-2-903435406135"
    bucket_path: "docker-sample"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
